import { useEffect, useState } from 'react'
import type { Lang } from '../../engines/language/languageEngine'
import { fetchAdminAiControls, fetchAdminAiDailyReport, fetchAdminHostInsights, updateAdminAiControl, type AiDailyReport, type AiSectionControl, type PlatformAdminHostInsight } from '../../shared/api/platformApi'

type Props = {
  lang: Lang
}

const copy = {
  ar: {
    eyebrow: 'توصيات التسعير',
    title: 'توصيات التسعير للمضيفين',
    subtitle: 'كل توصية هنا حقيقية — مبنية على بيانات حجز فعلية وتم توليدها بواسطة الذكاء الاصطناعي بناءً على طلب المضيف.',
    admin: 'الإدارة',
    loading: 'جار التحميل...',
    error: 'تعذر تحميل التوصيات.',
    empty: 'لا توجد توصيات مولّدة بعد.',
    generated: 'إجمالي التوصيات',
    emailed: 'تم إرسالها بالبريد',
    read: 'تمت قراءتها',
    host: 'المضيف',
    listing: 'الإعلان',
    message: 'التوصية',
    controls: 'إدارة أقسام الذكاء الاصطناعي', on: 'يعمل', off: 'متوقف',
    controlNote: 'عند التشغيل: يراقب AI القسم، يكتشف المشاكل، ويقترح الإجراءات. الاسترداد، صرف الأموال، إيقاف الحسابات، والنشر تحتاج موافقتك دائماً.',
    morning: 'التقرير التنفيذي الصباحي', generatedAt: 'تم التحديث', pending: 'بانتظار المراجعة', disputes: 'نزاعات مفتوحة', hosts: 'المضيفون', security: 'أحداث أمنية (٧ أيام)',
  },
  en: {
    eyebrow: 'Pricing insights',
    title: 'Host pricing insights',
    subtitle: 'Every recommendation here is real — built from real booking data and generated by AI at a host\'s request.',
    admin: 'Admin',
    loading: 'Loading...',
    error: 'Could not load insights.',
    empty: 'No insights generated yet.',
    generated: 'Total generated',
    emailed: 'Emailed',
    read: 'Read',
    host: 'Host',
    listing: 'Listing',
    message: 'Recommendation',
    controls: 'AI section management', on: 'ON', off: 'OFF',
    controlNote: 'When ON: AI monitors the section, detects problems, and recommends actions. Refunds, money release, account suspension, and deployment always require your approval.',
    morning: 'Morning executive report', generatedAt: 'Updated', pending: 'Awaiting review', disputes: 'Open disputes', hosts: 'Hosts', security: 'Security events (7 days)',
  },
}

export function AiBrainPage({ lang }: Props) {
  const isAr = lang === 'ar'
  const t = copy[lang]
  const [insights, setInsights] = useState<PlatformAdminHostInsight[]>([])
  const [totals, setTotals] = useState({ generated: 0, emailed: 0, read: 0 })
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading')
  const [message, setMessage] = useState('')
  const [controls, setControls] = useState<AiSectionControl[]>([])
  const [report, setReport] = useState<AiDailyReport | null>(null)
  const [updating, setUpdating] = useState('')

  useEffect(() => {
    void load()
  }, [])

  async function load() {
    setStatus('loading')
    try {
      const [response, controlResponse, reportResponse] = await Promise.all([fetchAdminHostInsights(), fetchAdminAiControls(), fetchAdminAiDailyReport()])
      setInsights(response.insights)
      setTotals(response.totals)
      setControls(controlResponse.controls)
      setReport(reportResponse.report)
      setStatus('ready')
    } catch (error) {
      setStatus('error')
      setMessage(error instanceof Error ? error.message : t.error)
    }
  }

  async function toggleControl(control: AiSectionControl) {
    setUpdating(control.section)
    try {
      const response = await updateAdminAiControl(control.section, !control.enabled)
      setControls(response.controls)
    } catch (error) {
      setMessage(error instanceof Error ? error.message : t.error)
    } finally {
      setUpdating('')
    }
  }

  const sectionName = (section: AiSectionControl['section']) => ({
    str: isAr ? 'الإيجار القصير STR' : 'Short-Term Rentals', hosts: isAr ? 'المضيفون' : 'Hosts', realestate: isAr ? 'العقارات' : 'Real Estate',
    commerce: isAr ? 'السوق والسيارات والإعلانات' : 'Marketplace, Cars & Ads', transport: isAr ? 'النقل SR' : 'SR Transport', finance: isAr ? 'المالية والإيرادات' : 'Finance & Revenue',
    trust: isAr ? 'الثقة والأمان' : 'Trust & Safety', operations: isAr ? 'الإدارة والتشغيل' : 'Administration & Operations',
  })[section]

  return (
    <main className="ai-brain-page" dir={isAr ? 'rtl' : 'ltr'}>
      <header className="ai-brain-top">
        <div>
          <span>◉</span>
          <strong>{t.title}</strong>
          <small>{t.eyebrow}</small>
        </div>
        <p>{t.subtitle}</p>
        <button onClick={() => (window.location.hash = '/admin/review')}>{t.admin}</button>
      </header>

      {status === 'loading' && <p>{t.loading}</p>}
      {status === 'error' && <p className="ai-brain-alert">{message}</p>}

      {status === 'ready' && (
        <>
          <section className="ai-panel-previews">
            <PreviewPanel title={t.generated} value={String(totals.generated)} />
            <PreviewPanel title={t.emailed} value={String(totals.emailed)} />
            <PreviewPanel title={t.read} value={String(totals.read)} />
          </section>

          <section className="ai-control-section">
            <h2>{t.controls}</h2>
            <p>{t.controlNote}</p>
            <div className="ai-control-grid">
              {controls.map((control) => (
                <article key={control.section} className={control.enabled ? 'enabled' : ''}>
                  <div><strong>{sectionName(control.section)}</strong><small>{control.enabled ? t.on : t.off}</small></div>
                  <button type="button" role="switch" aria-checked={control.enabled} disabled={updating === control.section} onClick={() => void toggleControl(control)}>
                    <span />
                  </button>
                </article>
              ))}
            </div>
          </section>

          {report && (
            <section className="ai-control-section">
              <h2>{t.morning}</h2>
              <p>{t.generatedAt}: <span dir="ltr">{new Date(report.generatedAt).toLocaleString(isAr ? 'ar' : 'en')}</span></p>
              <div className="ai-panel-previews">
                <PreviewPanel title={t.hosts} value={String(report.hosts)} />
                <PreviewPanel title={t.pending} value={String(report.listingsPending)} />
                <PreviewPanel title={t.disputes} value={String(report.openDisputes)} />
                <PreviewPanel title={t.security} value={String(report.securityEventsLast7Days)} />
              </div>
            </section>
          )}

          {insights.length === 0 ? (
            <p>{t.empty}</p>
          ) : (
            <section className="ai-improvements-column">
              {insights.map((insight) => (
                <article className="ai-improvement-card" key={insight.id}>
                  <div>
                    <strong>{insight.host?.displayName || t.host}</strong>
                    <small>{insight.listing?.titleAr || insight.listing?.titleEn || t.listing}</small>
                    <p>{isAr ? insight.messageAr : insight.messageEn || insight.messageAr}</p>
                  </div>
                </article>
              ))}
            </section>
          )}
        </>
      )}
    </main>
  )
}

function PreviewPanel({ title, value }: { title: string; value: string }) {
  return (
    <article>
      <h2>{title}</h2>
      <strong>{value}</strong>
    </article>
  )
}
